'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'..'),C=require('../dist/lottery-core.js');
const ctx={window:{}};vm.createContext(ctx);for(const f of ['solar-terms','data','editorial','editorial-notes','lottery-profiles'])vm.runInContext(fs.readFileSync(path.join(root,'dist',f+'.js'),'utf8'),ctx);
const foods=JSON.parse(JSON.stringify(ctx.window.FOODS)),profiles=JSON.parse(JSON.stringify(ctx.window.LOTTERY_PROFILES));
const events=C.eventsFrom(ctx.window.SOLAR_TERM_TIMES,ctx.window.SOLAR_TERM_NAMES),now=Date.parse('2026-09-28T12:00:00Z');
const prefs={avoid:[],excludeText:'',flavors:['crisp'],effort:1,buy:'both',adventure:1};
const opts=(patch={})=>({foods,profiles,prefs,events,slots:C.nextSix(events,now),seed:'test-seed',...patch});
const draw=patch=>C.draw(opts(patch));
function makePlan(){return {id:'stable-plan',createdAt:now,updatedAt:now,revision:0,prefs,slots:draw()};}

test('declared recipes: all 55 signatures match; disabled candidates stay explicit',()=>{assert.equal(foods.length,55);for(const f of foods)assert.equal(C.signature(f),profiles[f.id].signature,f.id);assert.equal(Object.values(profiles).filter(p=>p.disabled).length,3);});
test('next six terms excludes current term and crosses New Year',()=>{const s=C.nextSix(events,now);assert.equal(s.length,6);assert.equal(s[0].name,'寒露');assert.equal(s[5].name,'冬至');assert.ok(s[5].endDay.startsWith('2027'));assert.ok(s.every((x,i)=>x.time>now&&(!i||x.time===s[i-1].end)));});
test('exact term instant counts as current, not future',()=>{const e=events.find(e=>e.year===2026&&e.index===18);assert.equal(C.nextSix(events,e.time)[0].index,19);});
test('data horizon fails closed instead of fabricating future terms',()=>{assert.throws(()=>C.nextSix(events,events.at(-3).time),/不足/);});
test('whole interval includes next-month choices when that month falls inside term',()=>{const s=C.nextSix(events,now).find(s=>s.name==='小雪');const f=foods.find(f=>f.id==='liyang-baixin');const d=C.candidateDays(f,profiles[f.id],s,events);assert.ok(d.length);assert.ok(d.every(x=>x.day.startsWith('2026-12')));});
test('late-month records do not recommend early February morels',()=>{const s=C.nextSix(events,Date.parse('2027-01-25T00:00:00Z'));const f=foods.find(f=>f.id==='jintang-fresh-morel');assert.equal(C.candidateDays(f,profiles[f.id],s[0],events).length,0);assert.ok(C.candidateDays(f,profiles[f.id],s[1],events).every(x=>x.day>='2027-02-21'));});
test('multi-origin crop cannot borrow another region season',()=>{const f=foods.find(f=>f.id==='foshougua-miao');const slots=C.nextSix(events,Date.parse('2027-06-21T00:00:00Z'));const summer=slots.flatMap(s=>C.candidateDays(f,profiles[f.id],s,events));assert.ok(summer.length);assert.ok(summer.every(x=>x.place==='贵州普定'));});
test('seed makes the full draw reproducible, unique, and within supported dates',()=>{const a=draw(),b=draw();assert.deepEqual(a,b);const ids=a.filter(s=>s.foodId).map(s=>s.foodId);assert.equal(ids.length,6);assert.equal(new Set(ids).size,ids.length);a.forEach(s=>assert.ok(s.availableDays.includes(s.eatDay)));});
test('recipe mutation fails closed rather than trusting old restrictions',()=>{const f=structuredClone(foods[0]);f.ingredients+=' 鸡蛋';assert.equal(C.eligible(f,profiles[f.id],prefs),false);assert.equal(C.eligible(f,undefined,prefs),false);});
test('unknown custom exclusion blocks every recommendation',()=>{assert.throws(()=>draw({prefs:{...prefs,excludeText:'火星果'}}),/未识别/);});
test('known aliases resolve to food IDs, not unchecked substring filters',()=>{const r=C.resolveExclusions('龙须菜，鲜芡实',foods);assert.equal(r.unknown.length,0);assert.ok(r.ids.has('foshougua-miao'));assert.ok(r.ids.has('jitoumi'));});
test('vegan excludes animal additions including eggs, dairy and optional honey',()=>{const p={...prefs,avoid:['vegan']};for(const f of foods){if(C.eligible(f,profiles[f.id],p))assert.ok(!profiles[f.id].avoid.some(x=>['egg','milk','honey','meat','seafood'].includes(x)));}const f=foods.find(f=>f.id==='wuding-jinquehua');assert.equal(C.eligible(f,profiles[f.id],p),false);});
test('seafood restriction excludes shrimp accompaniment to vegetables',()=>{const f=foods.find(f=>f.id==='pucai');assert.equal(C.eligible(f,profiles[f.id],{...prefs,avoid:['seafood'],effort:2}),false);});
test('no-cook never includes recipes needing cooking, even fungi or seafood',()=>{for(const f of foods.filter(f=>C.eligible(f,profiles[f.id],{...prefs,effort:0})))assert.equal(f.category,'fruit');});
test('overly restrictive draw leaves honest blanks, never relaxation',()=>{const s=draw({prefs:{...prefs,effort:0,avoid:['vegan','milk']}});assert.ok(s.filter(x=>!x.foodId).length>0);assert.ok(s.filter(x=>x.foodId).every(x=>profiles[x.foodId].effort===0));});
test('locks stay fixed in a full redraw',()=>{const a=draw(),locked={[a[0].key]:a[0].foodId,[a[2].key]:a[2].foodId};const b=draw({seed:'different',locked});assert.equal(b[0].foodId,a[0].foodId);assert.equal(b[2].foodId,a[2].foodId);assert.throws(()=>draw({locked:{[a[0].key]:'not-a-food'}}),/锁定/);});
test('one-slot reroll preserves other five and forbids previous ID',()=>{const a=draw();for(let k=0;k<6;k++){const locked=Object.fromEntries(a.filter((s,i)=>i!==k&&s.foodId).map(s=>[s.key,s.foodId]));const b=draw({locked,exclude:{[a[k].key]:a[k].foodId},seed:'reroll'});a.forEach((s,i)=>{if(i!==k)assert.equal(b[i].foodId,s.foodId);});assert.notEqual(b[k].foodId,a[k].foodId);}});
test('augmenting matching reserves a singleton slot',()=>{const fsyn=[{id:'a',name:'a',recipeTitle:'a',ingredients:'a',steps:['a'],peakMonths:[1,2],placeSeasons:[{name:'x',months:[1,2],source:'https://example.com'}]},{id:'b',name:'b',recipeTitle:'b',ingredients:'b',steps:['b'],peakMonths:[1],placeSeasons:[{name:'x',months:[1],source:'https://example.com'}]}];const ps=Object.fromEntries(fsyn.map(f=>[f.id,{signature:C.signature(f),avoid:[],effort:0,family:'fruit'}]));const slots=[{key:'one',startDay:'2027-01-01',endDay:'2027-01-02'},{key:'two',startDay:'2027-02-01',endDay:'2027-02-02'}];const s=C.draw({foods:fsyn,profiles:ps,prefs,events,slots,seed:'b'});assert.equal(s[0].foodId,'b');assert.equal(s[1].foodId,'a');});
test('12-month property sweep: all restrictions, unique IDs, legal date windows',()=>{for(let m=1;m<=12;m++){for(const avoid of [[],['egg'],['milk'],['soy'],['seafood'],['vegan']]){const p={...prefs,avoid,effort:2},s=draw({prefs:p,slots:C.nextSix(events,Date.parse(`2027-${String(m).padStart(2,'0')}-01T00:00:00Z`)),seed:'sweep'+m});const ids=s.filter(x=>x.foodId).map(x=>x.foodId);assert.equal(new Set(ids).size,ids.length);for(const x of s.filter(x=>x.foodId)){const f=foods.find(f=>f.id===x.foodId);assert.ok(C.eligible(f,profiles[f.id],p));assert.ok(x.eatDay>=x.startDay&&x.eatDay<=x.endDay);}}}});
test('time zones: China, Taipei, UTC and New York DST',()=>{assert.equal(C.stamp(C.zonedTime('2027-01-05','19:00','Asia/Shanghai')),'20270105T110000Z');assert.equal(C.zonedTime('2027-01-05','19:00','Asia/Taipei'),C.zonedTime('2027-01-05','19:00','Asia/Shanghai'));assert.equal(C.stamp(C.zonedTime('2027-07-05','19:00','America/New_York')),'20270705T230000Z');assert.equal(C.stamp(C.zonedTime('2027-01-05','19:00','America/New_York')),'20270106T000000Z');assert.throws(()=>C.zonedTime('2027-03-14','02:30','America/New_York'),/不存在/);});
test('ICS: six standalone events, UTF-8 folds <=75 octets, CRLF, no RRULE',()=>{const ics=C.makeICS(makePlan(),foods,{},now);assert.equal((ics.match(/BEGIN:VEVENT/g)||[]).length,6);assert.equal((ics.match(/BEGIN:VALARM/g)||[]).length,6);assert.ok(!ics.includes('RRULE'));assert.ok(!ics.replaceAll('\r\n','').includes('\n'));for(const line of ics.split('\r\n'))assert.ok(Buffer.byteLength(line)<=75);const unfolded=ics.replace(/\r\n /g,'');assert.ok(unfolded.includes('采购搜索词'));assert.ok(unfolded.includes('到货与保存'));assert.ok(unfolded.includes('注意'));assert.ok(unfolded.includes('DTSTART:20261009T110000Z'));});
test('ICS UID stable across redraw, SEQUENCE increases, no preference disclosure',()=>{const p=makePlan(),a=C.makeICS(p,foods,{},now);p.slots=draw({seed:'new'});p.revision++;p.updatedAt+=1000;const b=C.makeICS(p,foods,{},now);assert.deepEqual(a.match(/^UID:.+$/gm),b.match(/^UID:.+$/gm));assert.ok(b.includes('SEQUENCE:1'));assert.ok(!b.includes('excludeText'));assert.ok(!b.includes('\"flavors\":'));});
test('ICS subset and invalid edit protection',()=>{const p=makePlan();assert.equal((C.makeICS(p,foods,{included:[p.slots[0].key]},now).match(/BEGIN:VEVENT/g)||[]).length,1);assert.throws(()=>C.makeICS(p,foods,{included:[]},now),/没有勾选/);assert.throws(()=>C.makeICS(p,foods,{eatDays:{[p.slots[0].key]:'2027-08-01'}},now),/范围/);assert.throws(()=>C.makeICS(p,foods,{lead:30},now),/提前/);});
test('past reminders move forward, expired food plan refuses export',()=>{const p=makePlan(),one=p.slots[0];const opts={included:[one.key]};const t=C.zonedTime(one.eatDay,'08:00',C.ZONE);const r=C.calendarEvents(p,foods,opts,t)[0];assert.ok(r.start>t);assert.ok(r.late);assert.throws(()=>C.calendarEvents(p,foods,opts,C.zonedTime(C.addDays(one.eatDay,1),'20:00',C.ZONE)),/已过/);});
test('ICS text injection escaped and emoji folded without splitting codepoints',()=>{assert.equal(C.escapeText('a,b;c\\d\r\nEND:VEVENT'),'a\\,b\\;c\\\\d\\nEND:VEVENT');const s='DESCRIPTION:'+('青菜🍃'.repeat(30));const out=C.fold(s);assert.equal(out.replace(/\r\n /g,''),s);assert.ok(!Buffer.from(out).toString().includes('\ufffd'));});
test('invalid preferences are rejected',()=>{assert.throws(()=>C.validatePrefs({...prefs,avoid:['unrecognized']}));assert.throws(()=>C.validatePrefs({...prefs,flavors:['crisp','soft','fruit']}));assert.throws(()=>C.validatePrefs({...prefs,effort:99}));});

test('uncertain oil ingredients fail closed for peanut exclusion',()=>{const f=foods.find(f=>f.id==='foshougua-miao');assert.equal(C.eligible(f,profiles[f.id],{...prefs,avoid:['peanut']}),false);});
