'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..'),C=require('../dist/lottery-core.js'),T=require('../dist/tarot-core.js'),S=require('../dist/tarot-spread.js'),ctx={window:{}};
vm.createContext(ctx);
for(const f of ['solar-terms','data','editorial','editorial-notes','lottery-profiles','lottery-senses'])vm.runInContext(fs.readFileSync(path.join(root,'dist',f+'.js'),'utf8'),ctx);
const foods=JSON.parse(JSON.stringify(ctx.window.FOODS)),profiles=JSON.parse(JSON.stringify(ctx.window.LOTTERY_PROFILES)),events=C.eventsFrom(ctx.window.SOLAR_TERM_TIMES,ctx.window.SOLAR_TERM_NAMES);
const now=Date.parse('2026-09-30T04:00:00Z'),opts=(patch={})=>({foods,profiles,events,now,...patch});
const added=['jianou-zhuilli','chongming-baibiandou','chongming-xiangsu-yu','xiangyin-santang-jiaotou','wenzhou-pancai'];
function round(seed){let r=S.cut(S.shuffle(seed),1);for(const i of [1,4,9])r=S.take(r,i);return r;}
function sample(time,n){const history=[],results=[];for(let i=0;i<n;i++){const result=S.resolve(opts({now:time,round:round('cycle-'+i),history}));assert.ok(!result.empty);results.push(result);history.push(result.foodId);}return results;}
test('catalog adds five distinct local food entries, not five renamed existing recipes',()=>{assert.equal(foods.length,67);assert.equal(new Set(foods.map(f=>f.id)).size,67);for(const id of added)assert.ok(foods.find(f=>f.id===id));});
test('new recipes and sensory fingerprints match explicit review metadata',()=>{for(const id of added){const f=foods.find(f=>f.id===id),p=profiles[id];assert.equal(C.signature(f),p.signature,id);assert.equal(C.sensorySignature(f),p.senses.signature,id);assert.ok(f.steps.length>=3);assert.ok(f.storage&&f.safety&&f.buy&&f.search&&f.sources.length>=2);assert.ok(f.placeSeasons.every(p=>p.source&&p.months.length));}});
test('all registered serving images exist and disclose their role',()=>{for(const f of foods){const m=T.mediaFor(f);if(!m)continue;assert.ok(fs.existsSync(path.join(root,'dist',m.src)),f.id);assert.ok(m.alt);if(f.tarotImage){assert.ok(m.note);if(m.kind==='ingredient')assert.match(T.imageNote(f),/原料|参考/);}}});
test('every food has an edible detail image, including the five former ingredient-only entries',()=>{
 for(const f of foods){const src=f.dishImage||f.cutImage;assert.ok(src,f.id);assert.ok(fs.existsSync(path.join(root,'dist',src)),f.id);}
 for(const id of added){const f=foods.find(f=>f.id===id);assert.equal(T.mediaFor(f).src,f.dishImage);assert.equal(f.cardImage,f.dishImage);assert.match(f.dishCaption,/生成示意图.*非实物摄影/);assert.match(f.cardImageAlt,/生成示意图/);assert.match(T.imageNote(f),/生成示意图.*非实物摄影/);}
});
test('exactly twelve existing fruit presentations are restored without inventing dish photos',()=>{const fruit=foods.filter(f=>f.category==='fruit'&&f.tarotImage?.kind==='fresh'&&!f.peakWindows);assert.equal(fruit.length,12);for(const f of fruit){assert.equal(f.tarotImage.src,f.cutImage);assert.match(f.tarotImage.note,/并非此配方的完整装盘/);}});
test('generated fruit illustrations remain labeled non-photographic',()=>{const f=foods.find(f=>f.id==='tongxiang-zhuili');assert.match(T.imageNote(f),/生成示意图.*非实物摄影/);});
test('invalid primary dish path is rejected instead of falling back to another image',()=>{const f=structuredClone(foods.find(f=>f.tarotImage));f.dishImage='assets/../private.png';assert.equal(T.mediaFor(f),null);});
test('habitat image alone cannot silently qualify a food for the draw',()=>{const f=structuredClone(foods[0]);delete f.dishImage;delete f.tarotImage;assert.ok(f.image);assert.equal(T.mediaFor(f),null);});
test('September pool expands from five to thirteen actual food IDs',()=>assert.equal(T.pool(opts()).length,13));
test('June pool contains six including fresh rakkyo and the two existing summer fruits',()=>{const p=T.pool(opts({now:Date.parse('2027-06-15T04:00:00Z')}));assert.equal(p.length,6);for(const id of ['xiangyin-santang-jiaotou','kuche-xiaobaixing','tongxiang-zhuili'])assert.ok(p.some(x=>x.food.id===id));});
test('October midmonth pool is eight, without shifting frost-gated fruits earlier',()=>{const p=T.pool(opts({now:Date.parse('2027-10-15T04:00:00Z')}));assert.equal(p.length,8);assert.ok(!p.some(x=>['lintong-huojing-shizi','minqing-tanxiang-olive'].includes(x.food.id)));});
test('three full September cycles cover every candidate once per cycle',()=>{const n=T.pool(opts()).length,r=sample(now,n*3);for(let i=0;i<3;i++)assert.equal(new Set(r.slice(i*n,(i+1)*n).map(x=>x.foodId)).size,n);for(let i=1;i<r.length;i++)assert.notEqual(r[i].foodId,r[i-1].foodId);assert.equal(r[n-1].remainingCount,0);assert.equal(r[n].cycleRestarted,true);});
test('cycle guarantee also holds for sparse February and June pools',()=>{for(const m of ['02','06']){const t=Date.parse(`2027-${m}-15T04:00:00Z`),n=T.pool(opts({now:t})).length,r=sample(t,n*3);for(let i=0;i<3;i++)assert.equal(new Set(r.slice(i*n,(i+1)*n).map(x=>x.foodId)).size,n);}});
test('one-card compatibility mode uses the same no-replacement cycle',()=>{const n=T.pool(opts()).length,h=[];for(let i=0;i<n*2;i++)h.push(T.draw(opts({seed:'one'+i,history:h})).foodId);assert.equal(new Set(h.slice(0,n)).size,n);assert.equal(new Set(h.slice(n)).size,n);});
test('newly eligible food gets a chance before a previous food repeats',()=>{const all=[{food:{id:'a'}},{food:{id:'b'}},{food:{id:'new'}}];assert.deepEqual(T.rotationCandidates(all,['a','b']).candidates.map(x=>x.food.id),['new']);});
test('out-of-season and excluded IDs do not occupy the active bag',()=>{const all=[{food:{id:'a'}},{food:{id:'b'}}];assert.deepEqual(T.rotationCandidates(all,['other','a']).candidates.map(x=>x.food.id),['b']);});
test('singleton keeps explicit repetition instead of inventing a dish',()=>{const f=T.pool(opts())[0].food,r=S.resolve(opts({round:round('single'),foods:[f],history:[f.id]}));assert.equal(r.foodId,f.id);assert.equal(r.repeated,true);assert.equal(r.remainingCount,0);});
test('restrictions and reviewed season dates still hold across all twelve months',()=>{for(let m=1;m<=12;m++)for(const avoid of [[],['vegan'],['meat'],['seafood'],['egg'],['milk'],['soy'],['wheat'],['peanut'],['sesame']]){const t=Date.parse(`2027-${String(m).padStart(2,'0')}-15T04:00:00Z`);for(const x of T.pool(opts({now:t,avoid}))){assert.ok(C.eligible(x.food,profiles[x.food.id],T.preferences(avoid)));assert.equal(x.place.day,C.dayAt(t));assert.ok(x.food.placeSeasons.some(p=>p.name===x.place.place&&p.months.includes(m)));}}});
test('fresh rakkyo does not appear as a year-round preserved product',()=>{for(let m=1;m<=12;m++){const p=T.pool(opts({now:Date.parse(`2027-${String(m).padStart(2,'0')}-15T04:00:00Z`)}));assert.equal(p.some(x=>x.food.id==='xiangyin-santang-jiaotou'),m===6);}});
test('pan-cai keeps Wenzhou winter and introduced Ningxia autumn separate',()=>{
 const f=foods.find(x=>x.id==='wenzhou-pancai');assert.equal(f.region,'浙江温州');assert.equal(f.lat,27.99);assert.equal(f.lon,120.70);
 for(const [date,origin] of [['2027-01-28','浙江温州'],['2027-02-15','浙江温州'],['2027-09-15','宁夏贺兰 · 温州盘菜引种'],['2027-10-15','宁夏贺兰 · 温州盘菜引种']]){
  const p=T.pool(opts({now:Date.parse(date+'T04:00:00Z')})).find(x=>x.food.id===f.id);assert.ok(p,date);assert.equal(p.place.place,origin);
 }
 for(const date of ['2027-01-15','2027-03-15','2027-07-15','2027-12-15'])assert.ok(!T.pool(opts({now:Date.parse(date+'T04:00:00Z')})).some(x=>x.food.id===f.id),date);
});
test('three disabled ingredients remain disabled despite larger pool',()=>{const ids=Object.keys(profiles).filter(id=>profiles[id].disabled);assert.equal(ids.length,3);for(const month of ['05','06','09'])assert.ok(T.pool(opts({now:Date.parse(`2027-${month}-15T04:00:00Z`)})).every(x=>!ids.includes(x.food.id)));});
test('live UI keeps full page-session draw history and no persistent personal tracking',()=>{const ui=fs.readFileSync(path.join(root,'dist/tarot-spread-ui.js'),'utf8');assert.ok(!/history=history\.slice\(-[25]\)/.test(ui));assert.ok(!/localStorage|sessionStorage|geolocation|DeviceMotion|fetch\(/.test(ui));assert.match(ui,/T\.mediaFor/);assert.match(ui,/remainingCount/);});
test('legacy entries retain month-based eligibility without new date windows',()=>{for(const f of foods.filter(f=>!f.peakWindows))for(let m=1;m<=12;m++)assert.equal(C.isPeakDay(f,`2027-${String(m).padStart(2,'0')}-15`),f.peakMonths.includes(m));});
